### ISSUE TITLE
ModuleNotFoundError: No module named 'p5'

### ISSUE THREAD

**Issue by CorrelateVisuals** [p5py/p5-examples#3]
When I try to run one of the programs it states that it can't find the to import module p5. Could anyone clarify what I'm doing wrong?

**Comment by abhikpal** [comment]
Looks like Python can't find p5 on your computer. How did you install p5? There are installation instructions on the ReadTheDocs website, if you want to take a look: http://p5.readthedocs.io/en/latest/install.html

**Comment by CorrelateVisuals** [comment]
Alright, thank you so much! I'm new to Python and had no clue how to install all the needed files. It mentions nowhere that you need to do this from the command line. But it worked now and runs like a charm. Let's get started!!!

**Comment by abhikpal** [comment]
> It mentions nowhere that you need to do this from the command line

I'll make sure to put this in all the READMEs!
